name: SellStick
main: com.acropolismc.play.sellstick.SellStick
version: 8.1.0.4
author: shmkane
website: https://github.com/shmkane/SellStick
depend: [Vault, MassiveCore]
softdepend: [Factions, Essentials]
commands:
   sellstick:
      description: Sell all items in a chest easily!
