name: SellStick
main: com.acropolismc.play.sellstick.SellStick
version: 8.0.8a
author: shmkane
website: http://acropolismc.com
depend: [Vault, Essentials]
softdepend: [Factions, Essentials, MassiveCore, LegacyFactions, ASkyBlock]
commands:
   sellstick:
      description: Sell all items in a chest easily!
