name: SellStick
main: com.acropolismc.play.sellstick.SellStick
version: 8.1.0.5L
author: shmkane
website: https://shmkane.github.io/SellStick/
depend: [Vault, LegacyFactions]
softdepend: [Factions, Essentials]
commands:
   sellstick:
      description: Sell all items in a chest easily!
