name: SellStick
main: com.acropolismc.play.sellstick.SellStick
version: 8.1.0.6
author: shmkane
website: https://github.com/shmkane/SellStick
depend: [Vault, Towny]
softdepend: [Essentials]
commands:
   sellstick:
      description: Sell all items in a chest easily!
